[package]
name = "xtools"
version = "0.0.0"
homepage = "https://github.com/SirWindfield/xtools"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/SirWindfield/xtools"
authors = ["Sven Lechner <SirWindfield@users.noreply.github.com>"]
edition = "2018"
